Material:
  font: overlays/font.material.xml
  light: materials/light.material.xml
 
SceneGraph:
  skyBox: models/skybox/skybox.scene.xml
  env: environments/001.scene.xml

Pipeline:
  - pipelines/forward.pipeline.xml
  - pipelines/deferred.pipeline.xml
  - pipelines/hdr.pipeline.xml
  - pipelines/custom.pipeline.xml
  
Camera:
  tx: 59
  ty: 11
  tz: -51
  rx: -20
  ry: 135
  rz: 0
  sx: 1
  sy: 1
  sz: 1
